const assert=require('node:assert/strict');
const P=require('../js/dayform-model.js');
const d=P.createDayformData();
assert.equal(d.settings.needsWelcome,true);assert.equal(Object.keys(d.presets).length,5);
P.applyPreset(d,'df-balance',d.selectedWeek);
const w=d.weeks[d.selectedWeek],first=w.items.find(i=>i.day==='Montag');
P.captureDay(w,'Montag');const frozen=P.clone(w.daySnapshots.Montag);
first.done=true;assert.ok(P.weekMetrics(w).percent>0);
first.day='Dienstag';P.captureDay(w,'Dienstag');
assert.equal(Object.values(w.daySnapshots).flatMap(s=>s.items).filter(i=>i.id===first.id).length,1);
const linked=P.editableItems(d).filter(i=>i.titleId===first.titleId);
first.title='Bewegung neu';first.cat='Familie';P.assignTitle(d,first,first.titleId);
assert.ok(linked.every(i=>i.title==='Bewegung neu'&&i.cat==='Familie'));
assert.deepEqual(w.daySnapshots.Montag,frozen);
const copy=P.clone(first);P.assignTitle(d,copy,'');assert.equal(copy.titleId,undefined);
assert.deepEqual(P.validateData(P.clone(d)),d);
const reset=P.clearPlanning(d,'all');assert.equal(reset.weeks[d.selectedWeek].items.length,0);assert.deepEqual(reset.standardTitles,d.standardTitles);assert.deepEqual(reset.looks,d.looks);
assert.throws(()=>P.captureDay(w,'Montag'));
const bad=P.clone(d);bad.weeks[d.selectedWeek].daySnapshots.Montag.date='bad';assert.throws(()=>P.validateData(bad));
const work=w.items.find(i=>i.day==='Montag'&&P.timeGroup(i.cat,d.masterData)==='work');
work.done=true;work.actualMinutes=190;
const m=P.dayMetrics(w,'Montag',d.masterData);assert.equal(m.actual,190);assert.equal(m.estimated,180);
const old=P.createData();P.ensureWeek(old,old.selectedWeek);const oldItems=P.clone(old.weeks[old.selectedWeek].items);P.ensureDayform(old);assert.deepEqual(old.weeks[old.selectedWeek].items.map(({titleId,...i})=>i),oldItems);
console.log('PASS: starter weeks, migration, linked title/category, frozen daily plans, actual comparison, reset, backup validation.');
