const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {pathToFileURL}=require('node:url'),P=require('../js/planner.js');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try {
  const page=await browser.newPage({viewport:{width:1560,height:1000}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  const data=P.createData(),week=P.ensureWeek(data,'2026-09-14');data.selectedWeek=week.weekStart;
  week.items=[{id:'job',title:'Visualisierung',day:'Montag',cat:'Kunde',start:'09:00',end:'10:15',done:false},{id:'sport',title:'Laufen',day:'Dienstag',cat:'Sport',start:'09:00',end:'10:00'},{id:'internal',title:'Admin',day:'Mittwoch',cat:'Admin',start:'09:00',end:'10:00',done:true,actualMinutes:60}];
  await page.goto(pathToFileURL(path.resolve(__dirname,'../../index.html')).href);
  await page.evaluate(data=>localStorage.setItem('jsOfficeWeek_v1',JSON.stringify(data)),data);await page.reload();
  const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('jsOfficeWeek_v1')));
  await page.locator('[data-id=job] .item-main').click();await page.locator('#feeDetails summary').click();
  await page.locator('#itemHourlyRate').fill('120,50');assert.match(await page.locator('#itemFeePreview').textContent(),/150,63/);
  await page.locator('#actualTimeDetails summary').click();await page.locator('#itemActualTime').fill('0:45');
  assert.match(await page.locator('#itemActualFeePreview').textContent(),/90,38/);
  await page.locator('#itemHourlyRate').fill('-2');await page.locator('#itemForm [type=submit]').click();
  assert.match(await page.locator('#itemError').textContent(),/Stundensatz/);assert.equal((await saved()).weeks[week.weekStart].items[0].hourlyRateCents,undefined);
  await page.locator('#itemHourlyRate').fill('120,50');
  const out=path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});
  await page.screenshot({path:path.join(out,'finance-editor.png')});
  await page.locator('#itemForm [type=submit]').click();await page.reload();
  assert.equal((await saved()).weeks[week.weekStart].items[0].hourlyRateCents,12050);
  await page.locator('[data-id=job] .resize-handle').press('ArrowDown');
  await page.locator('[data-section=month]').click();assert.match(await page.locator('#monthPanel [data-finance=done]').textContent(),/^0,00/);
  await page.locator('[data-section=week]').click();await page.locator('[data-id=job] .item-check').check();
  await page.locator('[data-section=month]').click();assert.match(await page.locator('#monthPanel [data-finance=done]').textContent(),/90,38/);
  await page.locator('[data-section=week]').click();await page.locator('[data-id=job] .resize-handle').press('ArrowUp');
  await page.locator('[data-id=job] .item-check').check();
  await page.locator('[data-section=month]').click();
  assert.equal(await page.locator('#monthPanel [data-finance=planned]').count(),0);
  assert.match(await page.locator('#monthPanel [data-finance=done]').textContent(),/90,38/);
  assert.match(await page.locator('#monthPanel .finance-unrated').textContent(),/ohne Stundensatz: 1/);
  await page.locator('[data-month-group=sport]').click();
  assert.match(await page.locator('#monthPanel [data-finance=done]').textContent(),/90,38/);
  await page.locator('#monthPanel').evaluate(p=>p.scrollTop=0);await page.screenshot({path:path.join(out,'finance-month.png')});
  await page.locator('[data-section=insights]').click();assert.match(await page.locator('#insightsPanel [data-finance=done]').textContent(),/90,38/);
  assert.equal(await page.locator('.completed-cards .group-sport').count(),0);
  await page.locator('.plan-comparison>summary').click();await page.locator('#analysisCapture').click();await page.locator('#captureForm [type=submit]').click();
  assert.equal(await page.locator('#insightsPanel .finance-summary').count(),1);
  await page.locator('#languageButton').click();await page.getByRole('menuitemradio',{name:'English',exact:true}).click();assert.match(await page.locator('#insightsPanel [data-finance=done]').textContent(),/90\.38/);
  assert.match(await page.locator('#insightsPanel .finance-heading').textContent(),/Fee overview/);
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#insightsPanel').evaluate(p=>p.scrollTop=0);await page.screenshot({path:path.join(out,'finance-mobile.png')});
  await page.setViewportSize({width:1560,height:1000});await page.locator('[data-section=week]').click();
  await page.locator('[data-id=sport] .item-main').click();assert.ok(await page.locator('#feeDetails').isHidden());await page.locator('#itemForm [data-close]').first().click();
  await page.locator('[data-id=job] .item-main').click();await page.locator('#itemHourlyRate').fill('');await page.locator('#itemForm [type=submit]').click();
  assert.equal((await saved()).weeks[week.weekStart].items[0].hourlyRateCents,null);
  await page.locator('[data-section=month]').click();assert.equal(await page.locator('#monthPanel [data-finance=planned]').count(),0);
  assert.deepEqual(errors,[]);console.log('PASS: rate validation, live preview, persistence/removal, done totals, missing rates, month filter, insights with/without snapshot, EN/mobile and personal exclusion.');
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
