const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const {pathToFileURL} = require('node:url');
const P = require('../js/planner.js');
(async()=>{
  const browser = await chromium.launch({headless:true,channel:'msedge'});
  const context = await browser.newContext({viewport:{width:1560,height:1000}});
  const page = await context.newPage(), errors = [];
  page.on('pageerror',error=>errors.push(error.message));
  const url = pathToFileURL(path.resolve(__dirname,'../../index.html')).href;
  const out = path.resolve(__dirname,'artifacts'); fs.mkdirSync(out,{recursive:true});
  const data = P.createData(), week = P.ensureWeek(data,'2026-09-14');
  week.items = [
    {id:'a',day:'Montag',start:'09:00',end:'11:00',title:'Kundenprojekt',cat:'Kunde',done:false},
    {id:'b',day:'Dienstag',start:'09:00',end:'10:00',title:'AI Research',cat:'AI / Firma',done:false}
  ];
  await page.goto(url); await page.evaluate(data=>localStorage.setItem('jsOfficeWeek_v1',JSON.stringify(data)),data); await page.reload();
  await page.locator('[data-section="insights"]').click();
  await page.locator('.plan-comparison>summary').click();
  assert.ok(await page.locator('#analysisCapture').isVisible());
  await page.locator('#analysisCapture').click();
  await page.locator('#captureForm button[type=submit]').click();
  assert.match(await page.locator('#sidebarProgress').textContent(),/0%/);
  const snapshot = await page.evaluate(()=>JSON.parse(localStorage.getItem('jsOfficeWeek_v1')).weeks['2026-09-14'].planSnapshot);
  await page.locator('[data-section="week"]').click();
  await page.locator('[data-id="a"] .item-check').check();
  assert.match(await page.locator('#sidebarProgress').textContent(),/67%/);
  await page.locator('[data-id="a"] .item-main').click();
  await page.locator('#itemEndButton').click();
  await page.locator('#itemEndList').getByRole('option',{name:'09:30',exact:true}).click();
  await page.locator('#itemForm button[type=submit]').click();
  await page.locator('[data-id="b"] .item-main').click(); await page.locator('#deleteItem').click();
  await page.locator('[data-section="insights"]').click();
  assert.match(await page.locator('#sidebarProgress').textContent(),/67%/);
  assert.match(await page.locator('.plan-changes').textContent(),/1 Plan-Einträge gelöscht/);
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('jsOfficeWeek_v1')).weeks['2026-09-14'].planSnapshot),snapshot);
  await page.screenshot({path:path.join(out,'analysis.png'),fullPage:true});
  await page.reload(); await page.locator('[data-section="insights"]').click();
  assert.match(await page.locator('#sidebarProgress').textContent(),/67%/);
  const beforeMonth = await page.evaluate(()=>localStorage.getItem('jsOfficeWeek_v1'));
  await page.locator('[data-section="month"]').click();
  assert.equal(await page.locator('.month-day').count(),30);
  await page.locator('#followingWeek').click();
  assert.match(await page.locator('#weekLabel').textContent(),/Oktober/);
  assert.equal(await page.locator('.month-day').count(),31);
  assert.equal(await page.evaluate(()=>localStorage.getItem('jsOfficeWeek_v1')),beforeMonth);
  await page.locator('#previousWeek').click();
  await page.screenshot({path:path.join(out,'month.png'),fullPage:true});
  await page.locator('[data-date="2026-09-17"]').click();
  assert.ok(await page.locator('.calendar').isVisible());
  assert.equal(await page.locator('#weekNumber').textContent(),'/ KW 38');
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-section="insights"]').click();
  assert.ok(await page.locator('#insightsPanel').isVisible());
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('[data-section="month"]').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:path.join(out,'month-mobile.png'),fullPage:true});
  assert.equal(errors.length,0,errors.join('\n'));
  await browser.close(); console.log('PASS: immutable plan capture, live completion, edits/deletion denominator, reload, month navigation without writes, day navigation, responsive analytics.');
})().catch(error=>{console.error(error);process.exit(1);});
